### DISCUSSION TITLE
Is it possible to run the Docker-based LHCI Server (patrickhulce/lhci-server) with basic auth enabled?

### DISCUSSION THREAD

**Discussion by lal65** [GoogleChrome/lighthouse-ci#1007] [Q&A] [answered]
Hello!

I was browsing the documentation (https://github.com/GoogleChrome/lighthouse-ci/tree/main/docs/recipes/docker-server) and I didn't see an obvious way of configuring basic auth with the pre-built image.

Is that something that users have to build a custom image for, or are there some sort of hidden/undocumented environment variables that might be used to configure this?

Thanks!

**Comment by fullyherge** [comment, marked as answer]
You can use the "LCHI_" env variables. I'm doing it like this, with `docker-compose.yml`:

```yaml
version: '3'
services:
  lhserver:
    image: patrickhulce/lhci-server:latest
    environment:
      LHCI_BASIC_AUTH__USERNAME: "..."
      LHCI_BASIC_AUTH__PASSWORD: "..."
    ports:
      - '9001:9001'
    volumes:
      - lhci-data:/data
volumes:
  lhci-data:
```

You can see more context [here for the env vars](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#environment-variables) and [this](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/recipes/docker-server/README.md#docker-compose) is where I got the compose file
