### DISCUSSION TITLE
My lighthouse action is setting GitHub status, but no artifacts or performance details. Why?

### DISCUSSION THREAD

**Discussion by MarkBennett** [GoogleChrome/lighthouse-ci#512] [Q&A]
Hi! Thanks for this great tool!

I've followed the Getting Started Guide and created a GitHub Action workflow, along with authorizing and installing the GitHub App in my repository and setting the `LHCI_GITHUB_APP_TOKEN` in my project environment, but I'm not seeing any of the status details (performance numbers) or a link to the artifact in my build.

As we're just starting out and our numbers aren't great, I'd like to focus on tracking these for now rather than adding an assertion and failing the build.

Here is my workflow file:

```
name: Lighthouse CI for Netlify sites
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Wait for the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: 'clhbid-com'
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.6.x
          lhci autorun --collect.url=${{ steps.netlify.outputs.url }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
```

And here is my `lighthouserc.js`:

```
module.exports = {
  ci: {
    upload: {
      target: 'temporary-public-storage',
    },
  },
};
```

This is what my projects environmet looks like:

![Screen Shot 2020-12-16 at 11 42 08 AM](https://user-images.githubusercontent.com/61872/102392008-bdae6f00-3f93-11eb-8987-30957b1de954.png)

Is anyone able to spot what's wrong? The Lighthouse job step looks good, and it's setting the GitHub status properly just without details or a link to the report. This is a typical run output.

```
Run npm install -g @lhci/cli@0.6.x
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/opt/hostedtoolcache/node/12.20.0/x64/bin/lhci -> /opt/hostedtoolcache/node/12.20.0/x64/lib/node_modules/@lhci/cli/src/cli.js
+ @lhci/cli@0.6.1
added 423 packages from 266 contributors in 13.321s
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
✅  GitHub token set
Healthcheck passed!

Running Lighthouse 3 time(s) on https://deploy-preview-106--clhbid-com.netlify.app
Run #1...done.
Run #2...done.
Run #3...done.
Done running Lighthouse!

Uploading median LHR of https://deploy-preview-106--clhbid-com.netlify.app/...success!
Open the report at https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1608143721623-80075.report.html
GitHub token found, attempting to set status...
GitHub accepted "success" status for "lhci/url/".

Done running autorun.
```

This what my check looks like in the UI. Note the lack of details or the annotations.

![Screen Shot 2020-12-16 at 11 44 41 AM](https://user-images.githubusercontent.com/61872/102392384-34e40300-3f94-11eb-9fb3-8a1caf316d06.png)

Thank you so much in advance! 🍻
