### DISCUSSION TITLE
Getting Started Guide for Appveyor integration

### DISCUSSION THREAD

**Discussion by nielsvhb** [GoogleChrome/lighthouse-ci#632] [Ideas]
Our company uses AppVeyor for our CI. The Getting started Guide hower, doesnt have a section on how to init Lighthouse with this tool. Is it possible to create a section for it?

Thanks in advance

**Comment by patrickhulce** [comment]
I'm not an Appveyor expert, but it should look pretty similar to the rest. The hardest part is getting Chrome available but it looks like it comes [preinstalled with Appveyor](https://www.appveyor.com/docs/windows-images-software/#web-browsers) (though you need to use Visual Studio 2019?).

Maybe this...?

```yaml
version: "{build}"
build: off
branches:  
  only:  
    - master
environment:  
  fast_finish: true
  matrix:
    - nodejs_version: "12" 
    - platform: x86
build: off
install:  
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g @lhci/cli@0.8.x
test_script:  
  - # whatever you need to do to build your project
  - lhci autorun
```

If you get it working, happy to add minimal example to the docs!
