### DISCUSSION TITLE
hand over extraHeaders inside github actions with secrets inside

### DISCUSSION THREAD

**Discussion by Tobi-mmt** [GoogleChrome/lighthouse-ci#925] [Q&A]
I have a nextjs app and I use github actions for the pipelines. So everytime I push changes on the branch, vercel build the nextjs application and this triggeres the following code:
```
name: E2E 
on: deployment_status

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: yarn

      - name: install
        run: yarn install --frozen-lockfile

      - name: Lighthouse Check
        run: yarn lhci autorun --extraHeaders.x-ci-shared-secret="${{ secrets.CI_SHARED_SECRET }}"
        env:
          PREVIEW_URL: ${{ github.event.deployment_status.target_url }}
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
```

The application is behind a middleware which allows to bypass the authentication if the `x-ci-shared-secret` field is set in the header. The only problem is now: How can I pass the header informations in the lhci autorun? 
It looks like the code above does not work. I also tried to hand over something like `--extraHeaders="{x-ci-shared-secret:${{ secrets.CI_SHARED_SECRET }}"` which also did not work.

The code of the app works fine, I am just struggeling with the way of handing over the headers inside af an github action yml. Any ideas or examples?
