### DISCUSSION TITLE
'lhci autorun' waits indefinitely at run #1 in gitlab runner CI

### DISCUSSION THREAD

**Discussion by jjunyjjuny** [GoogleChrome/lighthouse-ci#936] [Q&A]
![스크린샷 2023-08-18 오후 3 35 28](https://github.com/GoogleChrome/lighthouse-ci/assets/41738385/0f1abf8a-7bb5-4ca2-8d1a-493f8557e26e)

```js
// .lighthouserc.js
module.exports = {
  ci: {
    collect: {
      url: ['http://localhost:8080/order/history'],
      settings: {
        chromeFlags: '--disable-gpu --no-sandbox',
        // skipAudits: ['canonical', 'uses-http2', 'uses-long-cache-ttl'],
      },
      allowOverwriteOfLatestBranchBuild: true,
    },
    upload: {
      target: 'lhci',
      serverBaseUrl: ...,
      token: ...,
    },
  },
}
```

```
// .lighthouse-ci

lighthouse-ci:
  stage: lighthouse
  image: node:16
  script:
    - apt update
    - apt install -y chromium
    - pnpm install
    - {next start command} & sleep 10 && {run lhci command}
```

hello. I want to run the nextjs project in gitlab runner and measure the performance, but it is no longer going on in 'run #1'.

'node:16 docker image' does not have chromium. So I'm installing it

any other essential libraries need like chromium? I'm guessing there's no library that Lighthouse essentially uses in a pure node environment(node:16 docker image)...

----- 

I tried using "cypress/browsers:node16.17.0-chrome106" docker image. 

I was able to get away from waiting indefinitely in run #1. Instead, the error message "Runtime error encountered: The page provided is not HTML (served as MIME type )." 

However, when requested with 'curl' (curl -v localhost:8080/order/history), text/html response came down normally..

-----  

Everything works fine in my local environment, but I'm not sure why it didn't work properly in the gitlab runner ci environment

I want to keep using "node:16" images
