### ISSUE TITLE
gitlab ci blocks during run

### ISSUE THREAD

**Issue by chenfan0** [GoogleChrome/lighthouse-ci#1031]
lighthouserc.js
```js
module.exports = {
    ci: {
        collect: {
            url: [
                'http://127.0.0.1:8088/'
            ],
            numberOfRuns: 3,
            startServerCommand: "PORT=8089 node src/server",
            settings: {
                hostname: '127.0.0.1',
                chromeFlags: ['--no-sandbox'],
            },
        },
        upload: {
            target: 'temporary-public-storage',
        }
    }
}
```
.gitlab-ci.yml
```yml
lhci:
  stage: test
  image: cypress/browsers:node-18.16.1-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
  script:   
    - npm install
    - npm install -g @lhci/cli@0.13.x
    - npm run build
    - lhci autorun --config=./lighthouserc.js || echo "LHCI failed!"
```
<img width="656" alt="image" src="https://github.com/GoogleChrome/lighthouse-ci/assets/83797583/95da36c4-a0ec-44ea-b01c-a2b67cc2c295">

**Comment by ydhnwb** [comment]
I also got this. Any solution?

**Comment by chenfan0** [comment]
> I also got this. Any solution?

no 😞

**Comment by lukaas33** [comment]
I have the same issue with the following CI config: 

```yml
lighthouse:
  stage: .pre
  image: cypress/browsers:node16.17.0-chrome106
  script:
    - npm install -g @lhci/cli@0.13.x
    - lhci autorun --upload.target=temporary-public-storage --collect.settings.chromeFlags="--no-sandbox" --collect.staticDistDir="wiki/pages" --collect.numberOfRuns=1 || echo "LHCI failed!"
```
