### ISSUE TITLE
How to upload the Lighthouse CI results as GitHub status checks?

### ISSUE THREAD

**Issue by Hongbo-Miao** [GoogleChrome/lighthouse-ci#122]
Originally asked at [Stack Overflow](https://stackoverflow.com/questions/59026591/how-to-upload-the-lighthouse-ci-results-as-github-status-checks). It would be great if someone can help me point the direction. Thanks!

---

I am trying to set/upload the [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci) results as GitHub status checks based on [this guide](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#github-app-method-recommended).

 1. Based on the guide, I installed and authorized the GitHub app
    Lighthouse CI.
 1. Then I set the token I got as `LHCI_GITHUB_APP_TOKEN`
    in the Travis Environment Variables.

This is the part of my [**.travis.yml**](https://github.com/Hongbo-Miao/hongbomiao.com/blob/master/.travis.yml).

```
language: node_js
node_js:
  - "12"

branches:
  only:
    - master

cache: yarn

before_install:
  - yarn global add @lhci/cli

install:
  - yarn install --frozen-lockfile

jobs:
  include:
    # other stages...

    - stage: lighthouse
      script:
        - yarn build
        - lhci autorun
      after_script:
        # Set the results as GitHub status checks
        - lhci upload
      addons:
        chrome: stable
```

`lhci autorun` succeed runnning.

However, when `lhci upload` runs, it returns error

>     Error: Must provide token for LHCI target
>         at runLHCITarget (/home/travis/.config/yarn/global/node_modules/@lhci/cli/src/upload/upload.js:212:29)
>         at Object.runCommand (/home/travis/.config/yarn/global/node_modules/@lhci/cli/src/upload/upload.js:323:14)
>         at run (/home/travis/.config/yarn/global/node_modules/@lhci/cli/src/cli.js:90:23)
>         at Object.<anonymous> (/home/travis/.config/yarn/global/node_modules/@lhci/cli/src/cli.js:118:1)
>         at Module._compile (internal/modules/cjs/loader.js:959:30)
>         at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
>         at Module.load (internal/modules/cjs/loader.js:815:32)
>         at Function.Module._load (internal/modules/cjs/loader.js:727:14)
>         at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)

These are my [pull request](https://github.com/Hongbo-Miao/hongbomiao.com/pull/365) and corresponding [Travis error log](https://travis-ci.com/Hongbo-Miao/hongbomiao.com/jobs/260056622#L390).

How to set up this token for LHCI target correctly to be able to upload the Lighthouse CI results as GitHub status checks? Thanks

---

**UPDATE:**

Based on the error, I traced to [here](https://github.com/GoogleChrome/lighthouse-ci/blob/18fcc3e730cc720756eba4b9a94a778b60d5e1e0/packages/cli/src/upload/upload.js#L212) in the source code, I found out that the token that requires is actually the Lighthouse CI server token.

    token: {
      type: 'string',
      description: 'The Lighthouse CI server token for the project, only applies to `lhci` target.',
    },

For how to set up t he Lighthouse CI server, please refer to [this guide](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#the-lighthouse-ci-server).

So I think `lhci upload` only applies if you have set up a Lighthouse CI server, which is not for setting the Lighthouse CI results as GitHub status checks.

But still I haven't figured out how to upload the Lighthouse CI results as GitHub status checks.
