### ISSUE TITLE
How to run lhci for both desktop and mobile with single command?

### ISSUE THREAD

**Issue by felixck12** [GoogleChrome/lighthouse-ci#138]
Hello. We are using lhci autorun in our github actions and we'd like to analyze some pages for both mobile and desktop using the emulatedFormFactor setting. We will be uploading the results to our own lhci server.

Our ideal end result would be to have a report rendered that displays both results for mobile and desktop the same way PageSpeed Insights give you a toggle between the mobile and desktop.
![image](https://user-images.githubusercontent.com/1291157/70108546-73fc1c00-15fe-11ea-95c1-abe8ea2f94c8.png)

Curious if there is a way to do this without needed to
A) Run two separate autorun commands with a config for mobile and one for desktop
B)  If we can avoid having to setup two separate projects for desktop and mobile on our server to avoid commit hash conflicts.

Thanks in advance!

**Comment by patrickhulce** [comment]
hey @felixck12 thanks for filing! Smoother mobile and desktop simultaneous support is on our radar since right now it's a bit complicated to get them to live together.

To get it working today:

- You can't use `lhci autorun`, must use `collect`/`assert`/`upload` separately.
- You'll need to invoke `collect` twice with the `--additive` flag, ensuring the mobile and desktop URLs are different
`lhci collect --additive --settings.configPath=./path/to/desktop-config.js --url=http://localhost/?desktop` 
`lhci collect --additive --settings.configPath=./path/to/mobile-config.js --url=http://localhost/?mobile` 
- Run the rest of the steps as usual `lhci assert; lhci upload`


So to answer your questions directly...

> Run two separate autorun commands with a config for mobile and one for desktop

Not a way around this, you'll have to collect two separate times with different settings.

> If we can avoid having to setup two separate projects for desktop and mobile on our server to avoid commit hash conflicts.

Yes, if you use `collect --additive` and the URLs are different they can live in the same project and builds.

**Comment by felixck12** [comment]
Thanks @patrickhulce I will give this a try.

**Comment by jzabala** [comment]
@patrickhulce what do you think about changing the `--config` option to an array of configs that are run in the specified order. 

Something like:

`lhci autorun --config=./path/to/desktop-config.js --config=./path/to/mobile-config.js`

**Comment by kmcrawford** [comment]
Is this still on the radar?  I see this issue is 6 months and still very much needed!

**Comment by patrickhulce** [comment]
Yes still on the radar @kmcrawford. This issue wouldn't unlock any new functionality you can't accomplish today though so it's definitely not high on the list. If you'd like it to be prioritized then +1 the issue itself (the first original comment).

I'd also suggest a recalibration of your expectations for how quickly single person open source projects can finish their entire backlog or you'll have many more disappointments to come, Lighthouse CI or otherwise ;)

**Comment by Kocal** [comment]
If it can helps anyone, this is how I get checks working for both desktop and mobile, by using separate `lhci upload` and playing with `--githubStatusContextSuffix`:

```yaml
- name: Installing Lighthouse CI
  run: npm install -g @lhci/cli@0.9.x

# @see https://github.com/GoogleChrome/lighthouse-ci/issues/138#issuecomment-561698511
- name: Run Lighthouse CI
  id: lighthouse
  uses: actions/github-script@v6
  env:
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  with:
      script: |
          const lighthouseConfig = require('./lighthouserc');
        
          // Healthcheck
          await exec.exec('lhci', ['healthcheck', '--fatal']);

          // Desktop
          for await (const url of lighthouseConfig.ci.collect.url) {
              await exec.exec('lhci', ['collect', '--additive', '--url', url, '--psiStrategy', 'desktop', '--settings.preset', 'desktop']);
          };

          await exec.exec('lhci', ['assert']);
          await exec.exec('lhci', ['upload', '--githubStatusContextSuffix', '/desktop']);

          // Cleanup
          await exec.exec('rm', ['-fr', '.lighthouseci']);

          // Mobile
          for await (const url of lighthouseConfig.ci.collect.url) {
              await exec.exec('lhci', ['collect', '--additive', '--url', url, '--psiStrategy', 'mobile']);
          };

          await exec.exec('lhci', ['assert']);
          await exec.exec('lhci', ['upload', '--githubStatusContextSuffix', '/mobile']);
```

**Comment by randychilau** [comment]
Hi All,

With the same hope as the post above, but for folks sailing the dark seas for a beginner example using the [instructions provided](https://github.com/GoogleChrome/lighthouse-ci/issues/138#issuecomment-561698511) in terms of files and code: 

>note: this post is way too long (sorry!) and is not a step by step ([official](https://github.com/GoogleChrome/lighthouse-ci/tree/main#quick-start), [google search](https://www.google.com/search?q=instructions+on+how+to+use+lighthouse+with+github+actions+for+CI)) on setting up Lighthouse CI in Github Actions. I was working on an existing lighthouse/github action setup.

Here is one way to get desktop/mobile lighthouse working:

Step 1:

create the following files in the  root directory:

`.lighthouserc.js`

>this will be the file used for assert and upload instructions, and should be named as below [or similar as instructed](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#configuration-file)

`.desktop-lighthouserc.js`

>this file will only contain instructions for the `collect` part of lighthouse for desktop run

`.mobile-lighthouserc.js`

>this file will only contain instructions for the `collect` part of lighthouse for mobile run

---

Step 2:

In the `.lighthouserc.js` file:
```javascript
module.exports = {
    "ci": {
      "assert": {
        "assertions": {
          "categories:performance": ["warn", {"minScore": .90}],
          "categories:accessibility": ["warn", {"minScore": .90}],
          "categories:best-practices": ["warn", {"minScore": .90}],
          "categories:seo": ["warn", {"minScore": .90}],
          }
        },
      "upload": {
        "target": "temporary-public-storage",
      },
    }
  };
```
>you can customize the [`assert`](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#assert) and [`upload`](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#upload) sections as desired. 

In the `.desktop-lighthouserc.js`:

```javascript
module.exports = {
  "ci": {
    "collect": {
      "settings": {
        "additive": "true",
        "preset": "desktop"
        },
      "staticDistDir": "./public",
      "url": [
        "http://localhost/company/about/index.html?desktop",
      ],
    }
  }
};
```
>In the desktop file, take note 
>- add `"additive": "true"`, `"preset": "desktop"` in settings
>- add `?desktop` to the end of all the urls you are checking
>- you can add further [settings](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#collect)

In the `.mobile-lighthouserc.js`:
```javascript
module.exports = {
  "ci": {
    "collect": {
      "settings": {
        "additive": "true"
      },
      "staticDistDir": "./public",
      "url": [
        "http://localhost/company/about/index.html?mobile",
      ],
    }
  }
};
```
>In the mobile file, take note 
>- add `"additive": "true"` in settings
>- add `?mobile` to the end of all the urls you are checking

---

Step 3:

for the `lighthouseci.yml`file (located at `.github/workflows/lighthouseci.yml`):

```yaml
name: lighthouseci
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "*.md"
      - "*.github/**"

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install && npm install -g @lhci/cli@0.11.x
      - run: CI=false npm run build
      - run: lhci collect --additive --config=.mobile-lighthouserc.js
      - run: lhci collect --additive --config=.desktop-lighthouserc.js
      - run: lhci assert
      - run: lhci upload
   ```

>p.s. I didn't know how to do the color code blocks,[ instructions here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) (for the above, I used ```yaml)

Result of sample run:
![image](https://github.com/GoogleChrome/lighthouse-ci/assets/90356410/3eb83266-5817-4b5b-b404-ae30c1c637d0)

![image](https://github.com/GoogleChrome/lighthouse-ci/assets/90356410/64e30530-3f3f-4823-9623-d3974f417d89)


Hope this is helpful to someone.

Cheers!

**Comment by codepuncher** [comment]
@Kocal and @randychilau, thank you both for your examples!

They have helped me to find an alternative approach that fits my workflow that I thought I'd share too in case it helps anyone:

```yml
name: Lighthouse

on:
  # This will run on manual requests
  workflow_dispatch:
  # This will run Lighthouse test after the cd/deployment workflow has completed
  workflow_run:
    workflows: [cd]
    types:
      - completed

# Set environment variables to be shared between jobs and steps.
env:
  LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ github.sha }}
  # Set a custom user agent for requests to the URL that is being tested.
  LHCI_COLLECT__SETTINGS__EMULATED_USER_AGENT: "custom-user-agent"
  # Set basic authentication credentials for requests to private sites (e.g. staging/UAT)
  LHCI_COLLECT__SETTINGS__EXTRA_HEADERS: '{"Authorization": "Basic <your base64 encoded username:password string>"}'
  LHCI_COLLECT__SETTINGS__ONLY_CATEGORIES: "performance"
  LHCI_COLLECT__URL: "https://example-uat.my-agency.com"
  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  LHCI_UPLOAD__TARGET: "temporary-public-storage"

jobs:
  mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install -g @lhci/cli@0.14.x
      - run: lhci autorun
        env:
          LHCI_COLLECT__SETTINGS__PSI_STRATEGY: "mobile"
          LHCI_UPLOAD__GITHUB_STATUS_CONTEXT_SUFFIX: "/mobile"

  desktop:
    needs: mobile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install -g @lhci/cli@0.14.x
      - run: lhci autorun
        env:
          LHCI_COLLECT__SETTINGS__PRESET: "desktop"
          LHCI_COLLECT__SETTINGS__PSI_STRATEGY: "desktop"
          LHCI_UPLOAD__GITHUB_STATUS_CONTEXT_SUFFIX: "/desktop"
```

This example:
1. Runs the Lighthouse workflow **after** the `cd` (deployment) workflow has been completed
2. Uses environment variables instead of config files or CLI flags; just my preference while testing
3. Shows how to access sites behind basic auth
4. Includes the GitHub Status context suffix for each job
5. Runs a mobile test *before* running a desktop test
6. Doesn't need to run separate `collect`, `audit` or `upload` commands. Just uses `autorun`
7. Uses the same URL for mobile and desktop

Hope it's helpful!

![Image](https://github.com/user-attachments/assets/e8f219bb-4fac-44c5-8985-cd6901115e3e)
![Image](https://github.com/user-attachments/assets/866a15c4-48ac-439d-abcb-a14149ba363a)
