### ISSUE TITLE
Can I specify path for local reports?

### ISSUE THREAD

**Issue by mikhailnetkachev-halolab** [GoogleChrome/lighthouse-ci#163]
### Question:
How can I specify path for reports to my local folder in config?
I have found nothing about this in [documentation](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/cli.md).

### Desired behavior:
After running "lhci autorun --config=./lighthouserc.yml" all reports fall into directory, for example, './reports/local'.

_lighthouserc.yml_
```
ci:
  collect:
    numberOfRuns: 1
    additive: true
    startServerCommand: npm run watch
    url:
      - https://localhost:3000/
  assert:
    lighthouse: all
    assertions:
      offscreen-images: 'off'
      uses-webp-images: 'off'
      color-contrast: 'off'
```

_package.json_
```
"dependencies": {
    "@lhci/cli": "^0.3.6",
    "@lhci/server": "^0.3.6",
  }
```
