### ISSUE TITLE
CircleCI - can't determine current branch

### ISSUE THREAD

**Issue by Tonyhliu** [GoogleChrome/lighthouse-ci#188]
I'm running into this issue when trying to run `lhci autorun` on CircleCI. Could someone advise on how to fix this?

![image](https://user-images.githubusercontent.com/16828863/72647620-cc2c7a80-392d-11ea-98d1-5a7c51988a5f.png)

**Comment by patrickhulce** [comment]
@Tonyhliu it should be pulling the branch from `CIRCLE_BRANCH` and not resorting to `git rev-parse --abbrev-ref HEAD`. Has it been unset by something else running?

What does `echo "$CIRCLE_BRANCH"` output?

Also what version of lhci are you using?

**Comment by Tonyhliu** [comment]
Hey @patrickhulce - thanks for the response. echoing `$CIRCLE_BRANCH` returns my feature branch. 

I'm on `"@lhci/cli": "^0.3.8"`

**Comment by patrickhulce** [comment]
As a test workaround could you try `export LHCI_BUILD_CONTEXT__CURRENT_BRANCH="$CIRCLE_BRANCH"` before you run `lhci autorun` just to make sure lhci is receiving *some* of the set environment variables?

This shouldn't be needing anything special though, other 0.3.8 deployments on circle are chugging along fine 🤔 Anything else unique about your environment that might be relevant?

**Comment by Tonyhliu** [comment]
Hm, looks like the test workaround failed as well. Seems like Circle isn't respecting anything I export.

![image](https://user-images.githubusercontent.com/16828863/72649513-bbcace80-3932-11ea-9081-89761ea03b09.png)

To my knowledge, nothing's unique about the environment, and `lhci autorun` works fine locally...

**Comment by patrickhulce** [comment]
Hm, I'm just not able to reproduce this :/

Here are my [logs](https://circleci.com/gh/patrickhulce/patrickhulce.com/8) and my [circle config](https://github.com/patrickhulce/patrickhulce.com/blob/a9a384e67db6829d56c3013ac1924eae8b743728/.circleci/config.yml). I have the token and server base URL set via environment variables in the circle CI repo settings.

Any differences you can see with your setup?

**Comment by Tonyhliu** [comment]
The only difference I'm seeing with the build process is this : 
![image](https://user-images.githubusercontent.com/16828863/72654837-2a655780-3946-11ea-86ad-1cd43ce89bfe.png)

Everything else is pretty much the same :(

**Comment by patrickhulce** [comment]
Hm well the fact that Circle is saying git behavior will be different makes me think that the git behavior will be different :)

When you tested the `LHCI_BUILD_CONTEXT__CURRENT_BRANCH="$CIRCLE_BRANCH"` it looks like they might have been in a separate yaml `steps` entries which wouldn't work because circle invokes a separate shell for each step. Did you put them both into the same step? i.e. `command: LHCI_BUILD_CONTEXT__CURRENT_BRANCH="$CIRCLE_BRANCH" lhci autorun`

**Comment by Tonyhliu** [comment]
I see what you mean. Unfortunately throwing them all in the same line still doesn't work :( 

![image](https://user-images.githubusercontent.com/16828863/72655767-90081280-394b-11ea-83eb-221cef7f7ee8.png)

**Comment by patrickhulce** [comment]
I am utterly perplexed why environment variables are not being passed to the LHCI node process. At this point I'm really not sure where to go 😞 

It has to be *somehow* related to the lack of git in your container since that appears to be the only difference we can see. Is the container you're using publicly available and/or is there any way I can try to reproduce this on my own?

**Comment by Tonyhliu** [comment]
@patrickhulce unfortunately not a public repo, but I can show you my config for Circle

`# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      - image: registry.******.com:5000/node10.4.0-alpine
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

    working_directory: ~/repo
    steps:
      - run: apk update && apk add --no-cache git bash curl 
      - checkout
      - setup_remote_docker
      - run: npm config set unsafe-perm true
      - run: npm install -g npm@">=5.7.1"
      - run: npm install -g @lhci/cli@0.3.0
      - run: npm ci
      - run: npm test
      - run: npm run build:lib
      - run: npm run build:js:prod
      - run:
          name: manually set current branch
          command: export LHCI_BUILD_CONTEXT__CURRENT_BRANCH="$CIRCLE_BRANCH"
      - run: echo ${LHCI_BUILD_CONTEXT__CURRENT_BRANCH}
      - run:
          name: lhci autorun
          command: echo $CIRCLE_BRANCH && LHCI_BUILD_CONTEXT__CURRENT_BRANCH="$CIRCLE_BRANCH" && lhci autorun
      - run:
          name: lhci autorun
          command: lhci autorun # run lighthouse CI`

**Comment by patrickhulce** [comment]
Ah, it's because you're not actually using 0.3.8. 

Support for Circle and `LHCI_BUILD_CONTEXT__CURRENT_BRANCH` were added later. Change `npm install -g @lhci/cli@0.3.0` to `npm install -g @lhci/cli@0.3.x` and you should be good to go.

**Comment by Tonyhliu** [comment]
That seemed to have fix that issue - but now I seem to be running into this issue with Chromium : 

![image](https://user-images.githubusercontent.com/16828863/72840563-613eb480-3c49-11ea-824e-de10fb7d481c.png)

This is my updated config : 

```
jobs:
  build:
    docker:
      - image: registry.******.com:5000/node10.4.0-alpine
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

    working_directory: ~/repo
    steps:
      - run: apk update && apk add --no-cache git bash curl chromium
      - checkout
      - setup_remote_docker
      - run: npm config set unsafe-perm true
      - run: npm install -g npm@">=5.7.1"
      - run: npm install -g @lhci/cli@0.3.x
      - run: npm ci
      - run: npm test
      - run: npm run build:lib
      - run: npm run build:js:prod
      - run:
          name: manually set current branch
          command: export LHCI_BUILD_CONTEXT__CURRENT_BRANCH="$CIRCLE_BRANCH"
      - run: echo ${LHCI_BUILD_CONTEXT__CURRENT_BRANCH}
      - run:
          name: lhci autorun
          command: echo $CIRCLE_BRANCH && LHCI_BUILD_CONTEXT__CURRENT_BRANCH="$CIRCLE_BRANCH" && lhci autorun
      - run:
          name: lhci autorun
          command: lhci autorun # run lighthouse CI
```
