### ISSUE TITLE
NO_FCP running in Gitlab serving React SPA with "serve" module

### ISSUE THREAD

**Issue by dericgw** [GoogleChrome/lighthouse-ci#196]
I am attempting to automate Lighthouse into our Gitlab pipeline and I cannot get it to run a successful test using the [ziet/serve](https://github.com/zeit/serve) module. Locally, this works fine, but when running in our pipeline, I get NO_FCP error. What is interesting is that when I serve the project using Webpack Dev Server to serve the site, it works as expected. Of course, the metrics are horrible because it is a dev server. 

Here is the section of my `gitlab-ci.yml`:

```
perf_test:
  image: cypress/browsers:node10.16.0-chrome77
  dependencies:
    - build
  stage: test
  script:
    - npm install
    - npm run lighthouse // lhci autorun
  artifacts:
    paths:
      - ./report.html
    expire_in: 7 days
```

And here is my `lighthouserc.json`

```
{
  "ci": {
    "collect": {
      "numberOfRuns": 3,
      "settings": {
        "chromeFlags": "--no-sandbox --headless",
        "useThrottling": true,
        "disable-storage-reset": true,
        "onlyCategories": [
          "performance",
          "accessibility",
          "best-practices"
        ]
      },
      "startServerCommand": "npm run serve",
      "url": [
        "http://localhost:6001/create-account"
      ]
    },
    "upload": {
      "target": "temporary-public-storage"
    }
  }
}

```

Any idea why this would not be running in Gitlab but runs fine locally and also why it works in Gitlab when I serve the site from Webpack Dev Server?
