### ISSUE TITLE
lhci command not found on circleci

### ISSUE THREAD

**Issue by nawazeverlane** [GoogleChrome/lighthouse-ci#244]
**circleci code:**

```
perf:
    docker:
      - image: circleci/node:12.16.1-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            - dependencies-{{ .Environment.CACHE_VERSION }}
      - run: yarn global add @lhci/cli@0.3.x
      - run:
          name: lhci autorun
          command: |
            lhci autorun
```

**circleci output:**

<img width="1277" alt="Screen Shot 2020-03-18 at 12 21 06 PM" src="https://user-images.githubusercontent.com/57152245/76998957-24263400-6913-11ea-989e-30afc80f9def.png">

**package.json code**

```
"start": "next start -p $PORT",
"serve:lhci": "NODE_ENV=production PORT=3005 yarn start"
```

**lighthouserc.json**

```
{
  "ci": {
    "collect": {
      "numberOfRuns": 3,
      "url": [
        "http://localhost:3005",
      ]
    },
    "assert": {
      "preset": "lighthouse:recommended",
      "assertions": {
        "offscreen-images": "off",
        "uses-webp-images": "off"
      }
    },
    "upload": {
      "target": "temporary-public-storage"
    }
  }
}

```

**Additional info:**
Circle CI env vars set: NPM_TOKEN, LHCI_GITHUB_APP_TOKEN
App: nextjs

This works fine on a different project where I used `sudo` to install `yarn global add @lhci/cli@0.3.x` and do need an `NPM_TOKEN`. If I used `sudo` to install, it errors with `unable to replace ${NPM_TOKEN}`. I'm not sure if `sudo` is the issue here, given the circle ci output in the image `@lhci/cli@0.3.x`  seems to have been installed.

Thanks for helping out! 🙏

**Comment by patrickhulce** [comment]
Yes, `sudo` is necessary in Circle CI's image for a global installation (see [getting started example](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#collect-lighthouse-results)). 

I don't really understand the point about `NPM_TOKEN`. Lighthouse CI doesn't need nor does it ever read an `NPM_TOKEN` environment variable, so just installing `lhci` with sudo shouldn't affect anything else in your build that requires an npm token.

If for some reason you can't use lhci globally you can always add the CLI to your package.json devDeps and run it through an npm package.json script instead.

**Comment by nawazeverlane** [comment]
@patrickhulce The `${NPM_TOKEN}` is there because the project installs a few node packages from a private npm. You're right, it has nothing to do with Lighthouse-ci.

**.npmrc**

```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}

```

Running `sudo yarn global add @lhci/cli@0.3.x` fails with `unable to replace ${NPM_TOKEN}`.

Let me give the `devDeps` a shot and report back. TY for the swift response in the meantime 👍

**Comment by nawazeverlane** [comment]
This is the full `.circleci/config.yml` if it helps,

```
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.16.1

version: 2.1
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths: .

  bundle_dependencies:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            - dependencies-{{ .Environment.CACHE_VERSION }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            - dependencies-{{ .Environment.CACHE_VERSION }}

      - run: yarn run lint
      - run: yarn run build

      - persist_to_workspace:
          root: ./
          paths:
            - .next

  perf:
    docker:
      - image: circleci/node:12.16.1-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            - dependencies-{{ .Environment.CACHE_VERSION }}
      - run:
          name: lhci autorun
          command: |
            lhci autorun

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_code:
          filters:
            branches:
              ignore: /develop|master/
      - bundle_dependencies:
          requires:
            - checkout_code
          filters:
            branches:
              ignore: /develop|master/
      - build:
          requires:
            - bundle_dependencies
          filters:
            branches:
              ignore: /develop|master/
      - perf:
          requires:
            - build
          filters:
            branches:
              ignore: /develop|master/

```

**Comment by patrickhulce** [comment]
> No luck with devDeps as well

Meaning you get the NPM token message when running `yarn install` or what? If this is just about your local `.npmrc` why not just install it globally in any other directory?

i.e. `cd /anywhere/but/your/repo && sudo npm install -g lhci@0.3.x && cd ~/back/to/your/repo`

**Comment by nawazeverlane** [comment]
@patrickhulce yarn install works fine.

It fails at `sudo yarn global add @lhci/cli@0.3.x` on circleci.

<img width="1277" alt="Screen Shot 2020-03-18 at 12 21 06 PM" src="https://user-images.githubusercontent.com/57152245/77007386-5ccd0a00-6921-11ea-9cd3-56f7512dbc65.png">

**Comment by nawazeverlane** [comment]
Got it working 🎉 

1. Added the `lhci` package to the `devDeps`
2. Added a script `"lhci": "lhci autorun",` to `package.json`.
3. Updated the circleci config to,
```
- run:
          name: lhci autorun
          command: |
            yarn run lhci
```

@patrickhulce Thank you for helping me out 💯❤️
