### ISSUE TITLE
Collect method "psi": should it throw "Chrome installation not found"?

### ISSUE THREAD

**Issue by yuriteixeira** [GoogleChrome/lighthouse-ci#414]
As far as I understood, while using the PageSpeed API (`--collect.method=psi`), the tests would run in Google's cloud instead of trying to find an instance of Chrome on my local environment and run (which motivated me to generate an API token in my Google Cloud account and favour this method, so I don't need to run it on my CI, implying I don't need to have Chrome installed on my CI environments).

Did I miss something or this is indeed a bug?

**NOTE**: Not even using `LHCITEST_IGNORE_CHROME_INSTALLATIONS` ([an option I found being used in an automated test for the `healthcheck` script](https://github.com/GoogleChrome/lighthouse-ci/blob/2607167e4c6214fe802d92bfd69b516bf6e9acfa/packages/cli/test/healthcheck.test.js#L155) made the check to be skipped (but maybe it just works if I call healthcheck explicitly, which is not the case - using `autorun`)

**Context:**
* Relates to: #340 
* Version used: `0.4.4`
* Command used: `lhci autorun --config=./lighthouse-ci.config.json --collect.url=https://some/url/with/index.html --collect.numberOfRuns=1 --collect.settings.chromeFlags=--no-sandbox --collect.settings.emulatedFormFactor=desktop --collect.settings.onlyCategories=["performance", "accessibility", "best-practices"] --collect.method=psi --collect.psiApiKey=some-token`
* Config used:
```json
{
  "ci": {
    "assert": {
      "assertions": {
        "resource-summary:document:size": ["error", {"maxNumericValue": 2200}],
        "resource-summary:stylesheet:size": ["error", {"maxNumericValue": 15000}],
        "resource-summary:font:size": ["error", {"maxNumericValue": 105000}],
        "resource-summary:image:size": ["error", {"maxNumericValue": 377006}],
        "resource-summary:script:size": ["error", {"maxNumericValue": 500000}]
      }
    },
    "upload": {
      "ignoreDuplicateBuildFailure": true,
      "urlReplacementPatterns": ["s#/[a-f0-9]+/#/#"],
      "serverBaseUrl": "http://some/server:9001/",
      "githubApiHost": "https://github.com/api/v3"
    }
  }
}

```

**Comment by patrickhulce** [comment]
Ah, you're right @yuriteixeira the Chrome installation healthcheck shouldn't apply when you're using the PSI collect method 👍 

It's a bug we'll fix :)

**Comment by yuriteixeira** [comment]
Thanks for the fast reply!

**Comment by Kosai106** [comment]
@patrickhulce I'm confused, I'm encountering this issue with the `0.9.x` version - Has a regression been introduced?

**Comment by patrickhulce** [comment]
Doesn't look like it.

https://github.com/GoogleChrome/lighthouse-ci/blob/72270e7cfed4018c414b4dc5251d87fc35b5eae3/packages/cli/src/healthcheck/healthcheck.js#L65-L72

Willing to share your full command + config?

**Comment by Kosai106** [comment]
Here's what the CircleCI job looks like currently, including the workaround.

```yml
frontend-lighthouse-check:
    <<: *defaults
    docker:
      - image: cimg/node:16.13.0
    parallelism: 5
    steps:
      - checkout
      - inject-bash-helpers
      - *inject-yarn-deps
      # -- Chrome install needed to prevent error
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      # -- End Chrome install
      - run:
          name: Run Lighthouse CI
          command: |
            yarn global add @lhci/cli@0.9.x
            lhci autorun --collect.method=psi --collect.psiApiKey=${GOOGLE_PSI_KEY} --collect.settings.emulatedFormFactor=desktop ----headful=false
```
