### ISSUE TITLE
The base report doesn't get updated when using temporary public storage

### ISSUE THREAD

**Issue by samuelfernandez** [GoogleChrome/lighthouse-ci#415]
Every time lhci is run using temporary public storage, the results are compared with an old base report. Somehow it seems that when lhci runs for master branch it doesn't update the base report.

This is my GitHub workflow file: https://github.com/ng-easy/platform/blob/master/.github/workflows/ci.yml

```yml
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }} # https://github.com/GoogleChrome/lighthouse-ci/issues/172
          fetch-depth: 20 # https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/troubleshooting.md

      - name: Lighthouse Audit
        uses: treosh/lighthouse-ci-action@v3
        with:
          configPath: ./lighthouserc.json
          runs: 3
          uploadArtifacts: true
          temporaryPublicStorage: true
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
```

I'm running the audit with an action, but exactly the same happens with `run: lhci autorun`

Maybe it is a configuration problem I don't see, so any help will be appreciated.
