### ISSUE TITLE
LHCI autorun in github action CI seems to cache some files ?

### ISSUE THREAD

**Issue by blephy** [GoogleChrome/lighthouse-ci#464]
I use LHCI in github action.

When i run the pipeline, LHCI find an invalid canonical url : `https://allandolle.fr/`. It should found http://localhost:3001/

The fact is there is no more `allandolle.fr` string anywhere in my source code so i'm guessing, is there a cache somewhere ?

Note i'm using Helmet with ReactJS to set links and meta dynamically.
If i run the production server in my laptop, then i launch a lighthouse report in chrome dev tools, i'm not getting the error.

Here is the pull request which failed : [Link to the repository](https://github.com/blephy/allandolle-portfolio/pull/37)
Here is the logs of the pipeline step : [Link to the github action LHCI step](https://github.com/blephy/allandolle-portfolio/runs/1195962733?check_suite_focus=true)

Github action step : 

```yml
- name: run Lighthouse CI
        run: |
          npm install @lhci/cli@0.5.0
          npx lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          PORT: 3001
          DOMAIN_NAME: localhost:3001
          API_URL: http://localhost:3001/api/v1
```

I'm asking before putting assertions ...
