### ISSUE TITLE
Assert is failing even though everything is fine.

### ISSUE THREAD

**Issue by M1ck0** [GoogleChrome/lighthouse-ci#509]
**Describe the bug**
I created a website using `NextJS`, and some tests are failing even tho everything is working correctly in production.

**To Reproduce**
1. Create a website using `NextJS`
2. Add Lighthouse CI configuration
3. use `"preset": "lighthouse:recommended"`
3. Build a website using `yarn build`
4. Assert will fail

**Expected behavior**
It should not fail

**Logs/Screenshots**
<img width="605" alt="Screenshot_20201214_133920" src="https://user-images.githubusercontent.com/19279947/102082785-d6434b80-3e12-11eb-9c5e-fd4cd9926490.png">

**Environment (please complete the following information):**
 - OS: Manjaro Linux
 - Browser Chrome, Brave, Firefox
 - Version 0.6.1

**Additional context**
This is my `lighthouse.yml` config

```yml
name: Lighthouse

on: [push, pull_request]

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - run: yarn install --frozen-lockfile

            - name: Build site
              run: yarn build

            - name: Run Lighthouse CI
              uses: treosh/lighthouse-ci-action@v3
              with:
                  configPath: "./lighthouserc.json"
                  temporaryPublicStorage: true
```
and this is `lighthouserc.json`
```json
{
  "ci": {
    "collect": {
      "url": [
        "http://localhost/index.html"
      ],
      "numberOfRuns": 3,
      "staticDistDir": ".next/server/pages/"
    },
    "assert": {
      "preset": "lighthouse:recommended"
    }
  }
}
```

If I remove `"preset": "lighthouse:recommended"` it won't fail, but then, what's the point

App is installable, `rel=cannonical` does exist on website. Splash screen is configured, and so on...
