### ISSUE TITLE
Quick start guide should explain how to pass LHCI_GITHUB_APP_TOKEN to Lighthouse CI GitHub App

### ISSUE THREAD

**Issue by janosh** [GoogleChrome/lighthouse-ci#521]
The docs for setting up the [Lighthouse CI GitHub App](https://github.com/apps/lighthouse-ci) could be improved.

It took way too long to [find out on a third-party site](https://dev.to/jakepartusch/the-best-way-to-automate-performance-checks-in-github-584e) how to pass the `LHCI_GITHUB_APP_TOKEN` to `lhci` in GitHub actions. Adding the final two lines in this snippet to the quick start guide at https://github.com/apps/lighthouse-ci would be immensely helpful.

```yml
- run: lhci autorun
  env:
    LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
```
