### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by ninjadev-64** [GoogleChrome/lighthouse-ci#542]
Hello,
Can someone please help me?
I have installed the GitHub App, and put the token in a secret.
This is my lighthouserc.js:
```
name: Build project and run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
```
But I am getting these logs:
```
Run npm install -g @lhci/cli@0.3.x
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/opt/hostedtoolcache/node/10.23.1/x64/bin/lhci -> /opt/hostedtoolcache/node/10.23.1/x64/lib/node_modules/@lhci/cli/src/cli.js
+ @lhci/cli@0.3.14
added 380 packages from 267 contributors in 19.308s
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
✅  GitHub token set
Healthcheck passed!

Started a web server on port 37481...
Done running Lighthouse!

GitHub token found, attempting to set status...
No LHRs for status check, skipping.

Done running autorun.
```
And nothing is getting shown in my status checks. I think that the problem is in `No LHRs for status check, skipping.`, but I don't know what that means and I can't find the solution.

I have been following the tutorials on web.dev (one of my favourite sites!) [here](https://web.dev/lighthouse-ci/).
I really would like the automated lighthouse checks so this would be helpful.

Sorry!
ninjadev64 (without the dash! I don't like other repos showing up in my recent repos)
