### ISSUE TITLE
Node versions, specifically using Node 12

### ISSUE THREAD

**Issue by royletron** [GoogleChrome/lighthouse-ci#545]
Hey Lighthousers.

I have been chasing a really odd bug when running lighthouse server locally and deploying to Heroku using the deployment instructions. I couldn't get anywhere with it until I read the Dockerfile that is also provided and spotted that is set to Node-12. I use 14 locally, which Heroku also infers when it's not explicitly set in the package.json. So I guess I recommend either popping it in the docs somewhere (it might be, but I couldn't find it) that you need to use 12, or explicitly setting it in the provided `package.json` for the Heroku example.

**Comment by patrickhulce** [comment]
Hm that's very strange @royletron thanks for filing!!

There shouldn't be anything Node 12 specific here, and using node 14 was not enough for me to repro :/ Heroku docs also seem to suggest [node 12 is the default](https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version) though they could be out of date.

If it appeared to be hanging on the migrations step, is it possible this was an intermittent database hang and/or slowness and that restarting would have fixed the issue regardless of node 14 -> node 12?

**Comment by balvig** [comment]
I unfortunately don't have much to add 🙇  except I am experiencing a similar issue and ended up stuck at `umzug.up()` as well.

The app was failing to boot with a clean setup on Heroku which prompted the debugging session, and forcing the app to use Node 12 fixed the issue:

```diff
--- a/package.json
+++ b/package.json
@@ -6,5 +6,8 @@
     "@lhci/server": "0.4.x",
     "pg": "^7.12.1",
     "pg-hstore": "^2.3.3"
+  },
+  "engines": {
+    "node": "12.x"
   }
 }
```

**Comment by lordnox** [comment]
I just found out that my problems I have on github actions is related to this:

```

  lhci12:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.8.x
          lhci autorun

  lhci17:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.8.x
          lhci autorun
```

lhci17 fails after ~2:30min with: 
```
Error: Lighthouse failed with exit code 1
    at ChildProcess.<anonymous> (/opt/hostedtoolcache/node/17.4.0/x64/lib/node_modules/@lhci/cli/src/collect/node-runner.js:120:21)
    at ChildProcess.emit (node:events:520:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

lhci12 works and completes.

There has to be something node-12 specific in the code?
