### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by debdutgoswami** [GoogleChrome/lighthouse-ci#657]
**Describe the bug**

I have setup a GitHub action to trigger on every PR to `main`. I am using it on a `Jekyll` site. It shows `SyntaxError: Unexpected token =`. It is working fine on my local machine but failing in pipeline.

**lighthouserc.js**

```javascript
module.exports = {
    ci: {
        collect: {
            staticDistDir: './_site',
        },
        upload: {
            target: 'temporary-public-storage',
        },
    },
};
```

**ci.yml**

```yml
name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install ruby and jekyll
        run: |
          sudo apt-get install ruby-full build-essential zlib1g-dev
          sudo gem install jekyll bundler
      - name: Install site packages
        run: |
          sudo bundle install
          sudo bundle exec jekyll build
      - name: run Lighhouse CI
        run: |
          sudo npm install -g @lhci/cli@0.8.x
          lhci autorun
```

**Logs/Screenshots**
![lhci](https://user-images.githubusercontent.com/40338044/126466118-9b0834a6-7162-4a1a-a2ca-96432dce95b3.png)

**Environment (please complete the following information):**
 - OS: ubuntu
 - Version: @lhci/cli@0.8.x

**Additional context**
