### ISSUE TITLE
[variance] capability to `assert`/`upload` multiple `collect`runs 

### ISSUE THREAD

**Issue by khangsfdc** [GoogleChrome/lighthouse-ci#686]
**Is your feature request related to a problem? Please describe.**
Yes, perf variance running lighthouse in the cloud due to ephemeral hardware variance (e.g. docker, VMs).

**Describe the solution you'd like**
The ability to upload(`lhci upload`) and assert  (`lhci assert`) multiple  collect (`lhci collect`) reports to the same build context.  `lhci` already supports uploading with [build context](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#build-context), so this option would just be extending that to allow accepting multiple reports.

Note this is different than using `numberOfRuns` config option.  Having this new option would allow for running `lhci collect` multiple times in CI on a *different* container each time -- which, with enough test runs and the ability to take a mean/median of the runs, would help to eliminate hardware variance outliers.  

Simplified example using circleci:

```yaml
jobs:
   lighthouse_run_1:
      docker:
         - image: patrickhulce/lhci-client
      steps:
         - run: lhci collect
         - run: lhci upload
   lighthouse_run_2:
      docker:
         - image: patrickhulce/lhci-client
      steps:
         - run: lhci collect
         - run: lhci upload
   lighthouse_assert:
       docker:
         - image: patrickhulce/lhci-client
       steps:
         # theoretical new addition to assert to allow for assertion against an average of the multiple reports in the same build
         - run: lhci assert --reportsLocation=<location of upload location reports>
```

**Describe alternatives you've considered**
* Not running lighthouse in CI to avoid variance.
* A/B testing in lighthouse-ci i.e. running `lhci` against 2 previous and current build on same run (same hardware).
