### ISSUE TITLE
Running lighthouse-ci/cli 0.8.2 in github action unable to connect to chromium

### ISSUE THREAD

**Issue by abossenbroek** [GoogleChrome/lighthouse-ci#795]
**Describe the bug**
I try to run @lhci/cli@0.8.2 in a github action in headless mode and it is unable to connect to chromium.

**To Reproduce**
1. I use the following github action

```yml
name: Lighthouse
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt-get install wget xvfb
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - name: cygal yarn install and build
        run: |
          cd cygal && yarn install && yarn build  # changing directory to go in app directory in mono repo
      - name: Install lighthouse and run
        run: |
          wget "https://download-chromium.appspot.com/dl/Linux_x64?type=snapshots" --no-check-certificate -q -O chrome.zip && unzip chrome.zip
          export CHROME_PATH="$(pwd)/chrome-linux/chrome"
          yarn global add lighthouse@9.6.1 @lhci/cli@0.8.2 chromium-launcher
          cd cygal && lhci autorun  # changing directory to go in app directory in mono repo
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
```

With the following `lighthouserc.js` 

```js
module.exports = {
  ci: {
    collect: {
      settings: { chromeFlags: '--no-sandbox  --headless --disable-gpu' },
    },
    upload: {
      target: 'temporary-public-storage',
    },
  },
};
```

2. The error I get from github action is,

```
yarn global add lighthouse@9.6.1 @lhci/cli@0.8.2
  cd cygal && export LIGHTHOUSE_CHROMIUM_PATH=/usr/bin/chromium; lhci autorun  --chromePath=/usr/bin/chromium
  shell: /usr/bin/bash -e {0}
  env:
    LHCI_GITHUB_APP_TOKEN: ***
yarn global v1.22.18
[1/4] Resolving packages...
warning lighthouse > intl-messageformat > intl-messageformat-parser@1.8.1: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
warning @lhci/cli > lighthouse > raven > uuid@[3](https://github.com/bossenbroek-ai-photo/cygal/runs/6452088532?check_suite_focus=true#step:7:3).3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[2/[4](https://github.com/bossenbroek-ai-photo/cygal/runs/6452088532?check_suite_focus=true#step:7:4)] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "lighthouse@9.6.1" with binaries:
      - lighthouse
      - chrome-debug
      - smokehouse
success Installed "@lhci/cli@0.8.2" with binaries:
      - lhci
Done in 10.30s.
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
✅  GitHub token set
Healthcheck passed!

Automatically determined ./public as `staticDistDir`.
Set it explicitly in lighthouserc.json if incorrect.

Started a web server on port 3917[5](https://github.com/bossenbroek-ai-photo/cygal/runs/6452088532?check_suite_focus=true#step:7:5)...
Running Lighthouse 3 time(s) on http://localhost:39175/index.html
Error: Lighthouse failed with exit code 1
Run #1...failed!
    at ChildProcess.<anonymous> (/home/runner/.config/yarn/global/node_modules/@lhci/cli/src/collect/node-runner.js:120:21)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
Mon, 1[6](https://github.com/bossenbroek-ai-photo/cygal/runs/6452088532?check_suite_focus=true#step:7:6) May 2022 12:34:4[7](https://github.com/bossenbroek-ai-photo/cygal/runs/6452088532?check_suite_focus=true#step:7:7) GMT LH:ChromeLauncher Waiting for browser.
Mon, 16 May 2022 12:34:47 GMT LH:ChromeLauncher Waiting for browser...
Mon, 16 May 2022 12:34:47 GMT LH:ChromeLauncher Waiting for browser.....
Mon, 16 May 2022 12:34:47 GMT LH:ChromeLauncher Waiting for browser.....✓
Mon, 16 May 2022 12:34:47 GMT LH:config:warn IFrameElements gatherer requested, however no audit requires it.
Mon, 16 May 2022 12:34:47 GMT LH:config:warn FormElements gatherer requested, however no audit requires it.
Mon, 16 May 2022 12:34:4[8](https://github.com/bossenbroek-ai-photo/cygal/runs/6452088532?check_suite_focus=true#step:7:8) GMT LH:status Connecting to browser
Mon, 16 May 2022 [12](https://github.com/bossenbroek-ai-photo/cygal/runs/6452088532?check_suite_focus=true#step:7:12):34:48 GMT LH:CriConnection:warn Cannot create new tab; reusing open tab.
Mon, [16](https://github.com/bossenbroek-ai-photo/cygal/runs/6452088532?check_suite_focus=true#step:7:16) May [20](https://github.com/bossenbroek-ai-photo/cygal/runs/6452088532?check_suite_focus=true#step:7:20)[22](https://github.com/bossenbroek-ai-photo/cygal/runs/6452088532?check_suite_focus=true#step:7:22) 12:34:48 GMT LH:status Disconnecting from browser...
Mon, 16 May 2022 12:34:48 GMT LH:CriConnection:error sendRawMessage() was called without an established connection.
Mon, 16 May 2022 12:34:48 GMT LH:GatherRunner disconnect:error sendRawMessage() was called without an established connection.
Mon, 16 May 2022 12:34:48 GMT LH:ChromeLauncher Killing Chrome instance [24](https://github.com/bossenbroek-ai-photo/cygal/runs/6452088532?check_suite_focus=true#step:7:24)7[45](https://github.com/bossenbroek-ai-photo/cygal/runs/6452088532?check_suite_focus=true#step:7:45)
Unable to connect to Chrome

Error: Process completed with exit code 1.
```

**Expected behavior**
I would expect lighthouse-ci/cli to be able to connect to chromium.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.0
 - Browser: chromium
 - Version: latest

**Additional context**
You can see the github action in my [repo](https://github.com/bossenbroek-ai-photo/cygal/actions)
