### ISSUE TITLE
Lighthouse local server setup

### ISSUE THREAD

**Issue by Ramya412** [GoogleChrome/lighthouse-ci#808]
I have been trying to set up local lighthouse server. I have followed step by step process which is documented in the below article. https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md

But currently stuck with lhci wizard. When I try lhci wizard with https://lhci-canary.herokuapp.com/ it works as expected and I am able to generate the token as well. I can conclude here I am doing something wrong with a lighthouse server setup for sure But unable to find exactly where I am going wrong. Could you please help. Attached error snapshot below
![Screenshot_2022-07-04-14-51-39-69_6012fa4d4ddec268fc5c7112cbb265e7](https://user-images.githubusercontent.com/61500685/177124932-54ce4779-b957-4eb6-b1e5-743dea0f13e6.jpg)

**Comment by voratham** [comment]
Have you tried to docker-compose.yaml ?

```yaml
version: '3'
services:
  lhserver:
    image: patrickhulce/lhci-server
    ports:
      - '9001:9001'
    volumes:
      - lhci-data:/data
volumes:
  lhci-data:
```
