### ISSUE TITLE
GitHub Status Checks is not seen in PR

### ISSUE THREAD

**Issue by zi-gae** [GoogleChrome/lighthouse-ci#859]
I love that this repo exists, and the great work you're putting in here

I'm having issues with getting the [GitHub Status Checks](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md#github-status-checks) working when following the docs

### Install App
I finished the execution success and install LightHouse CI GitHub App, but I can't see page performance

### PR Action comment
![image](https://user-images.githubusercontent.com/39829378/210924325-e3be67df-e492-4a05-b612-8848dce629c6.png)

![image](https://user-images.githubusercontent.com/39829378/210923515-5e31a603-dd34-4c98-acb9-fdd6b36ec092.png)
code is here.
```js
// .lighthouserc.js
module.exports = {
  ci: {
    collect: {
      startServerCommand: 'yarn start',
      startServerReadyPattern: 'ready on',
      url: ['http://localhost:4000/union'],
      numberOfRuns: 1,
      settings: {
        preset: 'desktop',
      },
    },
    upload: {
      target: 'temporary-public-storage',
    },
    server: {},
  },
};
```

```
// package.json
"script": {
  "light-house": "lhci autorun --config=./.lighthouserc.js",
  ...,
}
```

```yml
# github actions
name: CI
on:
  pull_request:
    branches:
      - '**'
jobs:
  lighthouseci:
    env:
      deploy_target: 'prod'
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set NPM
        run: |
          echo @myrealtrip:registry=https://npm.pkg.github.com/ > .npmrc
          echo //npm.pkg.github.com/:_authToken=$NPM_TOKEN >> .npmrc
      - run: cat .npmrc
      - run: npm i -g yarn
      - run: yarn
      - run: yarn build
      - run: yarn light-house
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
```
