### ISSUE TITLE
Server setup issues. Server Documentation.

### ISSUE THREAD

**Issue by GreedyA1** [GoogleChrome/lighthouse-ci#98]
Hello I have trouble setting up diff server on Google Kubernetes Engine.  I am new to Google Cloud, I apologize if I'm asking too simple Question. I am having uploading the report or seeing it after on Google Cloud. Maybe I misunderstood some steps of setup, the documentation on google cloud kubernetes was too short for beginners. **Could you give me help with my current errors?**

**My travis yml.** (note I moved lighthouse as a last point, I want deployment to firebase to be complete.) 
```
dist: xenial
language: node_js
node_js:
  - "11"
addons:
  chrome: stable # make sure to have Chrome available
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - npm install -g @lhci/cli@0.3.x # install LHCI
script:
  - echo "Deploying!"
  - npm install
  - cd functions && npm install
  - cd ../ && npm run build -- --prod
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
  - lhci autorun --config=./lighthouserc.json

```
**My lighthouserc.json**
```
{
  "ci": {
    "collect": {
      "numberOfRuns": 3
    },
    "assert": {
      "preset": "lighthouse:recommended",
      "assertions": {
      }
    },
    "upload": {
      "serverBaseUrl": "https://**.**.**.**"
    }
  }
}

```
When I try to go to public IP (**.**.**.** can't show it) provided by Google Kubernetes, I het Cannot GET / 404 on the page. 
![image](https://user-images.githubusercontent.com/18186211/68995787-eead0380-08aa-11ea-94c3-7f8ece253cc0.png)

Also In my logs I can see. 

![image](https://user-images.githubusercontent.com/18186211/68995856-df7a8580-08ab-11ea-8425-51f24bb87354.png)

![image](https://user-images.githubusercontent.com/18186211/68995881-210b3080-08ac-11ea-8b06-dba1b724cff9.png)

In my travis logs I get this error at the end of the log. One thing I noticed the request goes to 443 port. Maybe that is the problem. 

```
FetchError: request to https://**.**.**.**/v1/projects/lookup failed, reason: connect ETIMEDOUT **.**.**.**:443
    at ClientRequest.<anonymous> (/home/travis/.nvm/versions/node/v11.15.0/lib/node_modules/@lhci/cli/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:193:13)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
WARNING: upload command failed.
assert command failed. Exiting with status code 1.
```
